---

- name: Update repositories cache. 
  apt:
    update_cache: yes


- name: Safe system upgrade via aptitude.
  apt: 
    upgrade: safe
    
    
- name: Install Nmap
  become: true
  apt:
    name: nmap
    update_cache: yes
    state: latest
