---

# use 'apt' or 'official' to get packages from standart
# repositories or from the tools' official websites

destination: "{{vHome}}/Tools_download"


gitlab_external_url: "http://192.168.33.9/gitlab"
gitlab_git_data_dir: "/var/opt/gitlab/git-data"
gitlab_edition: "gitlab-ce"
gitlab_version: ''
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_config_template: "mygitlab.rb.j2"
gitlab_package_version_separator: '='
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
gitlab_download_validate_certs: true
gitlab_restart_handler_failed_when: 'gitlab_restart.rc != 0'
gitlab_extra_settings:
  - unicorn:
      - key: "port"
        value: 8088
